### PR TITLE
Integrates Credentials Vocabulary; new Contexts

### PR DESCRIPTION
**Pull request by ottonomy**
This allows "id" to be used instead of "@id", and aliases "type" to "@type". This simplifies our OBI-backwards-compatible approach with a forward-looking JSON-LD approach. It requires existing values for "type" to be mapped in the context, so ("email", "signed", and "hosted") have been added to the contexts.

Follows from Manu's recommendation in his document review. http://etherpad.badgealliance.org/obi-vocab-review-credcg

Bugfix: Updates "obi" mapping to current value. 
** FOR DISCUSSION **: Are we going to move the URL of this published page to http://specification.openbadges.org ? @threeqube @cmcavoy

### CODE REVIEW

**Comment by threeqube** [comment]
@ottonomy Hmmm, not sure. Let me think about this.

**Comment by threeqube** [comment]
> ** FOR DISCUSSION **: Are we going to move the URL of this published page to http://specification.openbadges.org ? @threeqube @cmcavoy

@ottonomy working with @jdotpz to make this update.

**Comment by threeqube** [comment]
DNS is all set for specification.openbadges.org. Thanks @jdoptz!

**Comment by ottonomy** [comment]
It is decided, then. Thanks, @threeqube, @jdotpz. I'll put in a pull
request to change the CNAME file in this github repo. @jdotpz, I suspect
this is going to require changing standard.openbadges.org back to a 301
redirect from DNS.

**Comment by threeqube** [comment]
:+1:

**Comment by jdotpz** [comment]
Sure thing, let me know when you pull the trigger and I'll change the DNS to my redirector.

**Comment by ottonomy** [comment]
Oh, didn't realize this pull request was still open and now it's kind of a different one. For discussion:

I'm proposing a bunch of changes based on feedback from Credentials Community Group. Created a draft Credentials context for credentials vocabulary, and reworked index.md to change a number of anchor ids and update definitions. Will go back and document better tomorrow.

**Pull request merged**
