### PR TITLE
Test some xAPI integrations to include earning Open Badges in activity streams

### PR DESCRIPTION
**Pull request by ottonomy**
Do not merge at this time. Posted for community feedback from Open Badges specification community and xAPI community.

The added xAPI verb "earned" and extensions for hosted and signed assertions aim to allow badges to be transported in an LRS (Learning Record Store) activity stream. A statement "X earned Y Open Badge" could be used to indicate badges had been earned. The object of the statement would be a link to the hosted assertion or the full JWS of the signed assertion.

### CODE REVIEW

**Comment by garemoko** [comment]
Thanks for this @ottonomy! 

A few comments (many of these are missing features rather than issues with what you've got):

* We'll also need to define an [attachment usageType](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#attachmentUsage). Possible something ending in "/xapi/attachment/open-badge"
* xapi/index.md should also reference the existing activity type of http://activitystrea.ms/schema/1.0/badge. 
* It's common to separate words in xapi IRIs with "-", but not essential. 
* It's uncommon for IRIs to end in .json, but I don't see this as a problem, and in fact it could be helpful. 
* I recommend replacing "{{ site.baseurl }}" with the actual URL of the current site. If the site moves location, we want the identifiers to remain the same. 

@brianjmiller - do you have any further comments on this? I'm expecting we'll replicate this in Registry once it's finalised.

**Comment by ottonomy** [comment]
Thanks @garemoko:

A couple of the points are Jekyll quirks. `.json` is required by Jekyll, because otherwise it sets the content-type to `application/octet-stream`.

I don't know how attachment usageType is used, but I'll look into it next week if nobody else has taken over before then. Feel free to send me pull requests to the xapi branch on https://github.com/ottonomy/openbadges-specification

**Comment by dret** [comment]
just a thought: activity streams have a "received" verb (in the 1.0 vocabulary) which in its example explicitly suggests that it could be used for badges. why not reuse this verb instead of minting a new one? http://dret.github.io/W3C/SocialWG/AS1-in-AS2.html#verb-definition-receive

**Comment by elf-pavlik** [comment]
In W3C Social WG we work on JSON-LD based Activity Streams 2.0
* http://www.w3.org/TR/2015/WD-activitystreams-core-20150129/
* http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/

Github repo: https://github.com/jasnell/w3c-socialwg-activitystreams/issues

I would suggest already aligning with those drafts!

**Comment by dlongley** [comment]
:+1: @elf-pavlik 

With JSON-LD (it's an RDF syntax) you can also define vocabulary terms ("verbs") like any other RDF vocabulary or reuse existing ones like schema.org. You should only have to define that stuff once and in one way.

**Comment by garemoko** [comment]
@dret We considered the activity streams received verb (and it's certainly still a possibility). The main reason we didn't use it was because it's quite generic, whereas we want to allow for the possibility of filtering just statements about getting open badges. We've found that generally its better to have more specific verbs as tools consuming the data can easily group verbs together, but can't so easily split them up.

**Comment by dret** [comment]
without descending into a philosophical debate here, but i think the overall goal of AS is to make verbs broad enough that reuse is possible. otherwise you have each application having its own flavor of one specific aspect what they care about, and you reinvent a whole new wheel every time.
what we are doing to solve the problem you are having is to allow our AS implementation to filter things not only by verb, but by other patterns of the AS objects as well. so if you really are only interested in one specific "receive" that has a specific object type in it, then you can say so. to me, that's a better way to reuse existing verbs and still allow consumers to be more specific, if they want to. but that clearly is a design question, and both design styles are possible.
currently, our filter is pure JSON which i don't really like that much. what i want to get to eventually is a AS-level "query/filter language", which would allow those things to be properly on the level of the AS model, and not on the JSON serialization level. we'll get there, eventually, but for now the rather primitive JSON-based model is good enough to get the job done.

**Comment by garemoko** [comment]
@dret yeh, certainly if xAPI allowed filter by Activity Type this would be the way to go. We can filter by recipe though, so it's still a valid point in that regard. I'm certainly not ardently against using the activity streams received verb. @ryansmith94 - do you or your glorious leader want to comment on this? I know Ben was pretty keen on 'earned'.

**Comment by elf-pavlik** [comment]
1. Activity Streams 2.0 (based on JSON-LD) moves away from using *verb* and instead uses JSON-LD @type to define type of an activity. Similar to http://schema.org/Action (see: https://github.com/jasnell/w3c-socialwg-activitystreams/issues/23#issuecomment-73223157)

2. One can use rdfs:subClassOf to create more specialized types of activities. Please see for example: http://www.w3.org/TR/2015/WD-activitystreams-vocabulary-20150129/#dfn-favorite (Extends:	Respond)

```ttl
as:Favorite a owl:Class ;    
  rdfs:label "Favorite"@en ;
  owl:equivalentClass as:Like ;
  rdfs:subClassOf as:Respond ;
  rdfs:comment "To Favorite/Like Something"@en .
```

For consumers not having capacity of RDFS inference ``` obi:Earn rdfs:subClassOf as:Achieve . ```
one can always just assert otherwise missing statement ``` "@type": ["obi:Earn", "as:Achieve"]```

Please see also http://schema.org/docs/full.html#Action we still explore various possibilities for aligning AS2.0 and schema.org!

HTH

**Comment by dret** [comment]
@elf-pavlik, i am curious how the *producer* of such an activity is supposed to know what the *consumer* is or is not capable of. i know that a while ago an explicit goal of AS2 was to never require RDF processing in the processing model. from what you're saying, it seems like this has changed. because the only way this can work robustly are two possibilities:
* require RDFS processing by consumers so that they infer the types
* require the base otherwise inferred triples to be added so than inference is not required
in any other scenario the activity would mean something different to RDFS- and non-RDFS-capable consumers, right?

**Comment by ryansmith94** [comment]
Just to be clear here, this is not in anyway for the Activity Streams specification, it's for the xAPI specification.

> We can filter by recipe though, so it's still a valid point in that regard.

This is true, we should potentially look into using that for the Badges CoP.

> Do you or your glorious leader want to comment on this? I know Ben was pretty keen on 'earned'.

Ben is set on using the verb "earned" because that is the word used on Open Badges website and we want to keep our vocab consistent with the OBs vocab. If this vocab is changing the word "earned" to "received" then I absolutely agree that we should used "received" instead. If not then we should either (1) look into how reasonable it will be to filter by verb and recipe using the xAPI, or (2) just stick with "earned".

**Comment by elf-pavlik** [comment]
@dret unless you need digitally signed Activities, *server* not *producer* could choose how to customize it's representation for particular *client* requesting it. In practice I would see everyone starting with assumptions that *client* doesn't have capacity to infer triples and just assert them in responses. I think we will start drifting if we try to continue discussing it on this thread. I would change the approach and ask what other mechanism you would suggest to **specialize**/**extend** existing Activity Stream terms. I have impression that you suggest here *"You can not extend AS1 verbs so you just should work with what you get from central controlled vocab"*, while IMO Semantic Web technologies provide elegant patterns also for this particular issue.
When it comes to filtering, by leveraging RDF model one can use mechanisms like [Linked Data Fragments](http://www.hydra-cg.com/spec/latest/linked-data-fragments/) which includes [Triple Pattern Fragments](http://www.hydra-cg.com/spec/latest/triple-pattern-fragments/)

**Comment by dret** [comment]
@elf-pavlik: activities need to be self-describing. if that depends on RDFS inference, then they are not, at least not for JSON consumers. originally, the goal was to not require RDF processing for AS2. if that changes, AS2 is not JSON-based anymore, but RDF-based, which would be different from what the WG charter requires. but i agree that this is not the right place to discuss this.

**Comment by elf-pavlik** [comment]
FYI, I just created a User Story for W3C Social WG, trying to capture requirement of defining specialization of existing core subtype of Activity:

https://www.w3.org/wiki/Socialwg/Social_API/User_stories#Using_custom_types_of_Activity

If you find such extensibility important in Activity Streams 2.0 specification, please send you feedback to *-comments* address mentioned in: https://www.w3.org/wiki/Socialwg#Email

Thank you!

**Comment by ottonomy** [comment]
With @garemoko's contribution, the xAPI/Badges Community of Practice thinks this is ready to be published as a first draft to be used with the current version of the xAPI, long term changes to the xAPI aside.

ping @threeqube @kayaelle @cmcavoy

**Comment by cmcavoy** [comment]
Looks great, thanks everyone! :+1:

**Comment by ottonomy** [comment]
@garemoko I saw while reviewing changed files that you defined [badgeassertion](https://github.com/ottonomy/openbadges-specification/blob/xapi/xapi/attachment/badge.json#L4) as: `"An attached Open Badge assertion. This is a png image containing additional metadata as defined by the Open Badges specification."`

In the Open Badges community, we've used the terms `assertion` and `baked badge image` to denote that the assertion itself is a component of the image, but they aren't the same. 

I could imagine implementations where having easy direct access to the assertion JSON as well as the baked image would be nice. It's easy but nontrivial to implement a badge image assertion extractor. In the existing badge ecosystem, sometimes issuers don't even bake the image themselves, instead relying on the Backpack Issuer API to bake the image for them, in which case the image may not be discoverable from the assertion itself (although it would be re-creatable), because the baked image property of the assertion is optional. Sorry it's a little complicated!

Do you have any ideas for reworking this definition a little or making both the image and the assertion available

**Comment by garemoko** [comment]
Thanks for picking that up. On that basis, the name and first sentence of the description need to be updated to make clear that this is a baked badge image being referenced here. The second sentence of the description correctly explains what's envisaged here. 

We do also include a link to the source image and to the hosted assertion within the statement. The former is part of the badge class activity definition extension and the later is stored in the badge assertion result extension. 

The prototype I'm working on actually uses to re-bake the badge without having to download the attachment from each statement as one example mechanism of displaying the badges (another part does actually use the attachment in order to demo that). No part of the prototype ever pulls metadata from the badge - it always uses the statement. 

I'll make a correcting PR now.

**Comment by ottonomy** [comment]
Cool, thanks. :thumbsup:

**Pull request closed without merging**
