### PR TITLE
Added accessibility extension

### PR DESCRIPTION
**Pull request by tailot**
A proposal to extend accessibility based on https://schema.org/CreativeWork
Vocabolary for accessibility proprieties: http://www.w3.org/wiki/WebSchemas/Accessibility

### CODE REVIEW

**Comment by ottonomy** [comment]
@tailot Thanks for contributing this extension idea! There are a couple little things to clean up in the JSON, but before proposing any edits, I wanted to chat with you a little bit about the purposes of the various properties referenced in the schema and maybe build a couple examples of extended badge objects that meet these purposes. I'll have a little bit of time for this in the next couple days, but I will do my best to move this forward, because accessibility is an area that really needs attention!

**Comment by ottonomy** [comment]
If this is ready by next week we could discuss it on Tuesday's BA Standard call. I think we need to develop a couple things before we could consider it ready:
* Define a couple clear use cases for adding this accessibility information to badge objects
* Develop a couple example implementations that serve the use cases and include them in documentation to be developed for /extensions/index.md
* Do a quick pass through all the possible property types to determine whether it is reasonable that that property could be used in a badge object (Assertion, BadgeClass or Issuer).
* Add all possible terms to the context file.

I can help on these actions late this week.

**Comment by tailot** [comment]
@ottonomy Thanks for the reply.

Example use case:
* Accessibility in a badge class: https://gist.github.com/tailot/6cb41e9d9256e22dba0c We can use the extension to allow an application to create accessible content from badge. Trivial example (json 2 html accessibility and microdata): https://gist.github.com/tailot/bfce1493cdfc3a0367d6 output https://gist.github.com/tailot/e08377832d0d677a5271
* Accessibility in a issuer class: https://gist.github.com/tailot/d4edf2a32dd8d92c16e3 In this case the extension indicates a resource with accessibility.

This is just a small idea!

**Comment by tailot** [comment]
Added documentation with possible values.

**Comment by ottonomy** [comment]
Great, great! I'll take a look at all this tomorrow. Thanks, @tailot.

**Comment by ottonomy** [comment]
@tailot: Sorry to have made you wait so long to start using this. Thanks for your well-developed code.

**Pull request merged**
